config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  # MFA routes
  resource :mfa, controller: "mfa", only: [ :new, :create ] do
    get :verify
    post :verify, to: "mfa#verify_code"
    delete :disable
  end

  # Uses basic auth - see config/initializers/sidekiq.rb
  mount Sidekiq::Web => "/sidekiq"

  # AI chats
  resources :chats do
    resources :messages, only: :create

    member do
      post :retry
    end
  end

  get "changelog", to: "pages#changelog"
  get "feedback", to: "pages#feedback"
  get "early-access", to: "pages#early_access"

  resource :registration, only: %i[new create]
  resources :sessions, only: %i[new create destroy]
  resource :password_reset, only: %i[new create edit update]
  resource :password, only: %i[edit update]
  resource :email_confirmation, only: :new

  resources :users, only: %i[update destroy] do
    delete :reset, on: :member
  end

  resource :onboarding, only: :show do
    collection do
      get :profile
      get :preferences
    end
  end

  namespace :settings do
    resource :profile, only: [ :show, :destroy ]
    resource :preferences, only: :show
    resource :hosting, only: %i[show update] do
      delete :clear_cache, on: :collection
    end
    resource :billing, only: :show
    resource :security, only: :show
  end

  resource :subscription, only: %i[new show] do
    get :success, on: :collection
  end

  resources :tags, except: :show do
    resources :deletions, only: %i[new create], module: :tag
  end

  namespace :category do
    resource :dropdown, only: :show
  end

  resources :categories, except: :show do
    resources :deletions, only: %i[new create], module: :category

    post :bootstrap, on: :collection
  end

  resources :budgets, only: %i[index show edit update], param: :month_year do
    get :picker, on: :collection

    resources :budget_categories, only: %i[index show update]
  end

  resources :merchants, only: %i[index new create edit update destroy]

  resources :transfers, only: %i[new create destroy show update]

  resources :imports, only: %i[index new show create destroy] do
    member do
      post :publish
      put :revert
      put :apply_template
    end

    resource :upload, only: %i[show update], module: :import
    resource :configuration, only: %i[show update], module: :import
    resource :clean, only: :show, module: :import
    resource :confirm, only: :show, module: :import

    resources :rows, only: %i[show update], module: :import
    resources :mappings, only: :update, module: :import
  end

  resources :accounts, only: %i[index new] do
    collection do
      post :sync_all
    end

    member do
      post :sync
      get :chart
      get :sparkline
    end
  end

  resources :accountable_sparklines, only: :show, param: :accountable_type

  namespace :account do
    resources :holdings, only: %i[index new show destroy]

    resources :transactions, only: %i[show new create update destroy] do
      resource :transfer_match, only: %i[new create]
      resource :category, only: :update, controller: :transaction_categories

      collection do
        post "bulk_delete"
        get "bulk_edit"
        post "bulk_update"
        post "mark_transfers"
        post "unmark_transfers"
      end
    end

    resources :valuations, only: %i[show new create update destroy]
    resources :trades, only: %i[show new create update destroy]
  end

  direct :account_entry do |entry, options|
    if entry.new_record?
      route_for "account_#{entry.entryable_name.pluralize}", options
    else
      route_for entry.entryable_name, entry, options
    end
  end

  resources :transactions, only: :index do
    collection do
      delete :clear_filter
    end
  end

  resources :rules do
    resources :triggers, only: %i[create update destroy]
    resources :actions, only: %i[create update destroy]
  end

  # Convenience routes for polymorphic paths
  # Example: account_path(Account.new(accountable: Depository.new)) => /depositories/123
  direct :account do |model, options|
    route_for model.accountable_name, model, options
  end
  direct :edit_account do |model, options|
    route_for "edit_#{model.accountable_name}", model, options
  end

  resources :depositories, except: :index
  resources :investments, except: :index
  resources :properties, except: :index
  resources :vehicles, except: :index
  resources :credit_cards, except: :index
  resources :loans, except: :index
  resources :cryptos, except: :index
  resources :other_assets, except: :index
  resources :other_liabilities, except: :index

  resources :securities, only: :index

  resources :invite_codes, only: %i[index create]

  resources :invitations, only: [ :new, :create, :destroy ] do
    get :accept, on: :member
  end

  resources :currencies, only: %i[show]

  resources :impersonation_sessions, only: [ :create ] do
    post :join, on: :collection
    delete :leave, on: :collection

    member do
      put :approve
      put :reject
      put :complete
    end
  end

  resources :plaid_items, only: %i[create destroy] do
    member do
      post :sync
    end
  end

  namespace :webhooks do
    post "plaid"
    post "plaid_eu"
    post "stripe"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :family
  has_many :taggings, dependent: :destroy
  has_many :transactions, through: :taggings, source: :taggable, source_type: "Account::Transaction"
  has_many :import_mappings, as: :mappable, dependent: :destroy, class_name: "Import::Mapping"

  validates :name, presence: true, uniqueness: { scope: :family }

  scope :alphabetically, -> { order(:name) }

  COLORS = %w[#e99537 #4da568 #6471eb #db5a54 #df4e92 #c44fe9 #eb5429 #61c9ea #805dee #6ad28a]

  UNCATEGORIZED_COLOR = "#737373"

  def replace_and_destroy!(replacement)
    transaction do
      raise ActiveRecord::RecordInvalid, "Replacement tag cannot be the same as the tag being destroyed" if replacement == self

      if replacement
        taggings.update_all tag_id: replacement.id
      end

      destroy!
    end
  end
end

app/models/transaction/tag.rb
class Transaction::Tag < ApplicationRecord
  belongs_to :family

  validates :name, :family, presence: true
  scope :alphabetically, -> { order(:name) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[]
  end
end

app/controllers/tag/deletions_controller.rb
class Tag::DeletionsController < ApplicationController
  before_action :set_tag
  before_action :set_replacement_tag, only: :create

  def new
  end

  def create
    @tag.replace_and_destroy! @replacement_tag
    redirect_back_or_to tags_path, notice: t(".deleted")
  end

  private

    def set_tag
      @tag = Current.family.tags.find_by(id: params[:tag_id])
    end

    def set_replacement_tag
      @replacement_tag = Current.family.tags.find_by(id: params[:replacement_tag_id])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[edit update destroy]

  def index
    @tags = Current.family.tags.alphabetically

    render layout: "settings"
  end

  def new
    @tag = Current.family.tags.new color: Tag::COLORS.sample
  end

  def create
    @tag = Current.family.tags.new(tag_params)

    if @tag.save
      redirect_to tags_path, notice: t(".created")
    else
      redirect_to tags_path, alert: t(".error", error: @tag.errors.full_messages.to_sentence)
    end
  end

  def edit
  end

  def update
    @tag.update!(tag_params)
    redirect_to tags_path, notice: t(".updated")
  end

  def destroy
    @tag.destroy!
    redirect_to tags_path, notice: t(".deleted")
  end

  private

    def set_tag
      @tag = Current.family.tags.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name, :color)
    end
end

app/views/tags/_badge.html.erb
<%# locals: (tag:) %>
<% tag ||= null_category %>

<span class="border text-sm font-medium px-2.5 py-1 rounded-full content-center"
      style="
      background-color: color-mix(in srgb, <%= tag.color %> 5%, white);
        border-color: color-mix(in srgb, <%= tag.color %> 10%, white);
        color: <%= tag.color %>;">
  <%= tag.name %>
</span>

app/views/tags/_form.html.erb
<div data-controller="color-avatar">
  <%= styled_form_with model: tag, class: "space-y-4", data: { turbo_frame: :_top } do |f| %>
    <section class="space-y-4">
      <div class="w-fit m-auto">
        <%= render partial: "shared/color_avatar", locals: { name: tag.name, color: tag.color } %>
      </div>
      <div class="flex gap-2 items-center justify-center">
        <% Tag::COLORS.each do |color| %>
          <label class="relative">
            <%= f.radio_button :color, color, class: "sr-only peer", data: { action: "change->color-avatar#handleColorChange" } %>
            <div class="w-6 h-6 rounded-full cursor-pointer peer-checked:ring-2 peer-checked:ring-offset-2 peer-checked:ring-blue-500" style="background-color: <%= color %>"></div>
          </label>
        <% end %>
      </div>
      <div class="relative flex items-center border border-gray-200 rounded-lg">
        <%= f.text_field :name, placeholder: t(".placeholder"), autofocus: true, required: true, data: { color_avatar_target: "name" } %>
      </div>
    </section>

    <section>
      <%= hidden_field_tag :tag_id, params[:tag_id] %>
      <%= f.submit %>
    </section>
  <% end %>
</div>

app/views/tags/_ruler.html.erb
<div class="bg-white">
  <div class="h-px bg-alpha-black-50 ml-4 mr-6"></div>
</div>

app/views/tags/_tag.html.erb
<%# locals: (tag:) %>

<div id="<%= dom_id(tag) %>" class="flex justify-between items-center p-4 bg-white">
  <div class="flex w-full items-center gap-2.5">
    <%= render partial: "shared/color_avatar", locals: { name: tag.name, color: tag.color } %>
    <p class="text-primary text-sm truncate">
      <%= tag.name %>
    </p>
  </div>
  <div class="justify-self-end">
    <%= contextual_menu do %>
      <div class="w-48 p-1 text-sm leading-6 text-primary bg-white shadow-lg shrink rounded-xl ring-1 ring-gray-900/5">
        <%= contextual_menu_modal_action_item t(".edit"), edit_tag_path(tag) %>

        <% if tag.transactions.any? %>
          <%= link_to new_tag_deletion_path(tag),
                    class: "block w-full py-2 px-3 space-x-2 text-red-600 hover:bg-red-50 flex items-center rounded-lg",
                    data: { turbo_frame: :modal } do %>
            <%= lucide_icon "trash-2", class: "w-5 h-5" %>
            <span><%= t(".delete") %></span>
          <% end %>
        <% else %>
          <%= contextual_menu_destructive_item t(".delete"), tag_path(tag), turbo_confirm: nil %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tags/edit.html.erb
<%= modal_form_wrapper title: t(".edit") do %>
  <%= render "form", tag: @tag %>
<% end %>

app/views/tags/index.html.erb
<header class="flex items-center justify-between">
  <h1 class="text-primary text-xl font-medium"><%= t(".tags") %></h1>

  <%= link_to new_tag_path, class: "btn btn--primary flex items-center gap-1 justify-center", data: { turbo_frame: :modal } do %>
    <%= lucide_icon "plus", class: "w-5 h-5" %>
    <p><%= t(".new") %></p>
  <% end %>
</header>

<div class="bg-white shadow-border-xs rounded-xl p-4">
  <% if @tags.any? %>
    <div class="rounded-xl bg-gray-25 space-y-1 p-1">
      <div class="flex items-center gap-1.5 px-4 py-2 text-xs font-medium text-secondary uppercase">
        <p><%= t(".tags") %></p>
        <span class="text-subdued">&middot;</span>
        <p><%= @tags.count %></p>
      </div>

      <div class="border border-alpha-black-25 rounded-md bg-white shadow-border-xs">
        <div class="overflow-hidden rounded-md">
          <%= render partial: @tags, spacer_template: "tags/ruler" %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="flex justify-center items-center py-20">
      <div class="text-center flex flex-col items-center max-w-[300px]">
        <p class="text-primary mb-1 font-medium text-sm"><%= t(".empty") %></p>
        <%= link_to new_tag_path, class: "w-fit flex text-white text-sm font-medium items-center gap-1 bg-gray-900 rounded-lg p-2 pr-3", data: { turbo_frame: "modal" } do %>
          <%= lucide_icon("plus", class: "w-5 h-5") %>
          <span><%= t(".new") %></span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tags/new.html.erb
<%= modal_form_wrapper title: t(".new") do %>
  <%= render "form", tag: @tag %>
<% end %>