config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  # MFA routes
  resource :mfa, controller: "mfa", only: [ :new, :create ] do
    get :verify
    post :verify, to: "mfa#verify_code"
    delete :disable
  end

  # Uses basic auth - see config/initializers/sidekiq.rb
  mount Sidekiq::Web => "/sidekiq"

  # AI chats
  resources :chats do
    resources :messages, only: :create

    member do
      post :retry
    end
  end

  get "changelog", to: "pages#changelog"
  get "feedback", to: "pages#feedback"
  get "early-access", to: "pages#early_access"

  resource :registration, only: %i[new create]
  resources :sessions, only: %i[new create destroy]
  resource :password_reset, only: %i[new create edit update]
  resource :password, only: %i[edit update]
  resource :email_confirmation, only: :new

  resources :users, only: %i[update destroy] do
    delete :reset, on: :member
  end

  resource :onboarding, only: :show do
    collection do
      get :profile
      get :preferences
    end
  end

  namespace :settings do
    resource :profile, only: [ :show, :destroy ]
    resource :preferences, only: :show
    resource :hosting, only: %i[show update] do
      delete :clear_cache, on: :collection
    end
    resource :billing, only: :show
    resource :security, only: :show
  end

  resource :subscription, only: %i[new show] do
    get :success, on: :collection
  end

  resources :tags, except: :show do
    resources :deletions, only: %i[new create], module: :tag
  end

  namespace :category do
    resource :dropdown, only: :show
  end

  resources :categories, except: :show do
    resources :deletions, only: %i[new create], module: :category

    post :bootstrap, on: :collection
  end

  resources :budgets, only: %i[index show edit update], param: :month_year do
    get :picker, on: :collection

    resources :budget_categories, only: %i[index show update]
  end

  resources :merchants, only: %i[index new create edit update destroy]

  resources :transfers, only: %i[new create destroy show update]

  resources :imports, only: %i[index new show create destroy] do
    member do
      post :publish
      put :revert
      put :apply_template
    end

    resource :upload, only: %i[show update], module: :import
    resource :configuration, only: %i[show update], module: :import
    resource :clean, only: :show, module: :import
    resource :confirm, only: :show, module: :import

    resources :rows, only: %i[show update], module: :import
    resources :mappings, only: :update, module: :import
  end

  resources :accounts, only: %i[index new] do
    collection do
      post :sync_all
    end

    member do
      post :sync
      get :chart
      get :sparkline
    end
  end

  resources :accountable_sparklines, only: :show, param: :accountable_type

  namespace :account do
    resources :holdings, only: %i[index new show destroy]

    resources :transactions, only: %i[show new create update destroy] do
      resource :transfer_match, only: %i[new create]
      resource :category, only: :update, controller: :transaction_categories

      collection do
        post "bulk_delete"
        get "bulk_edit"
        post "bulk_update"
        post "mark_transfers"
        post "unmark_transfers"
      end
    end

    resources :valuations, only: %i[show new create update destroy]
    resources :trades, only: %i[show new create update destroy]
  end

  direct :account_entry do |entry, options|
    if entry.new_record?
      route_for "account_#{entry.entryable_name.pluralize}", options
    else
      route_for entry.entryable_name, entry, options
    end
  end

  resources :transactions, only: :index do
    collection do
      delete :clear_filter
    end
  end

  resources :rules do
    resources :triggers, only: %i[create update destroy]
    resources :actions, only: %i[create update destroy]
  end

  # Convenience routes for polymorphic paths
  # Example: account_path(Account.new(accountable: Depository.new)) => /depositories/123
  direct :account do |model, options|
    route_for model.accountable_name, model, options
  end
  direct :edit_account do |model, options|
    route_for "edit_#{model.accountable_name}", model, options
  end

  resources :depositories, except: :index
  resources :investments, except: :index
  resources :properties, except: :index
  resources :vehicles, except: :index
  resources :credit_cards, except: :index
  resources :loans, except: :index
  resources :cryptos, except: :index
  resources :other_assets, except: :index
  resources :other_liabilities, except: :index

  resources :securities, only: :index

  resources :invite_codes, only: %i[index create]

  resources :invitations, only: [ :new, :create, :destroy ] do
    get :accept, on: :member
  end

  resources :currencies, only: %i[show]

  resources :impersonation_sessions, only: [ :create ] do
    post :join, on: :collection
    delete :leave, on: :collection

    member do
      put :approve
      put :reject
      put :complete
    end
  end

  resources :plaid_items, only: %i[create destroy] do
    member do
      post :sync
    end
  end

  namespace :webhooks do
    post "plaid"
    post "plaid_eu"
    post "stripe"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/account/transaction/provided.rb
module Account::Transaction::Provided
  extend ActiveSupport::Concern

  def fetch_enrichment_info
    return nil unless provider

    response = provider.enrich_transaction(
      entry.name,
      amount: entry.amount,
      date: entry.date
    )

    response.data
  end

  private
    def provider
      Provider::Registry.get_provider(:synth)
    end
end

app/models/account/transaction/transferable.rb
module Account::Transaction::Transferable
  extend ActiveSupport::Concern

  included do
    has_one :transfer_as_inflow, class_name: "Transfer", foreign_key: "inflow_transaction_id", dependent: :destroy
    has_one :transfer_as_outflow, class_name: "Transfer", foreign_key: "outflow_transaction_id", dependent: :destroy

    # We keep track of rejected transfers to avoid auto-matching them again
    has_one :rejected_transfer_as_inflow, class_name: "RejectedTransfer", foreign_key: "inflow_transaction_id", dependent: :destroy
    has_one :rejected_transfer_as_outflow, class_name: "RejectedTransfer", foreign_key: "outflow_transaction_id", dependent: :destroy
  end

  def transfer
    transfer_as_inflow || transfer_as_outflow
  end

  def transfer?
    transfer.present?
  end

  def transfer_match_candidates
    candidates_scope = if self.entry.amount.negative?
      family_matches_scope.where("inflow_candidates.entryable_id = ?", self.id)
    else
      family_matches_scope.where("outflow_candidates.entryable_id = ?", self.id)
    end

    candidates_scope.map do |match|
      Transfer.new(
        inflow_transaction_id: match.inflow_transaction_id,
        outflow_transaction_id: match.outflow_transaction_id,
      )
    end
  end

  private
    def family_matches_scope
      self.entry.account.family.transfer_match_candidates
    end
end

app/models/family.rb
class Family < ApplicationRecord
  include Syncable, AutoTransferMatchable

  DATE_FORMATS = [
    [ "MM-DD-YYYY", "%m-%d-%Y" ],
    [ "DD.MM.YYYY", "%d.%m.%Y" ],
    [ "DD-MM-YYYY", "%d-%m-%Y" ],
    [ "YYYY-MM-DD", "%Y-%m-%d" ],
    [ "DD/MM/YYYY", "%d/%m/%Y" ],
    [ "YYYY/MM/DD", "%Y/%m/%d" ],
    [ "MM/DD/YYYY", "%m/%d/%Y" ],
    [ "D/MM/YYYY", "%e/%m/%Y" ],
    [ "YYYY.MM.DD", "%Y.%m.%d" ]
  ].freeze

  has_many :users, dependent: :destroy
  has_many :accounts, dependent: :destroy
  has_many :plaid_items, dependent: :destroy
  has_many :invitations, dependent: :destroy

  has_many :imports, dependent: :destroy

  has_many :entries, through: :accounts
  has_many :transactions, through: :accounts
  has_many :trades, through: :accounts
  has_many :holdings, through: :accounts

  has_many :tags, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :merchants, dependent: :destroy

  has_many :budgets, dependent: :destroy
  has_many :budget_categories, through: :budgets

  validates :locale, inclusion: { in: I18n.available_locales.map(&:to_s) }
  validates :date_format, inclusion: { in: DATE_FORMATS.map(&:last) }

  def balance_sheet
    @balance_sheet ||= BalanceSheet.new(self)
  end

  def income_statement
    @income_statement ||= IncomeStatement.new(self)
  end

  def sync_data(start_date: nil)
    update!(last_synced_at: Time.current)

    accounts.manual.each do |account|
      account.sync_later(start_date: start_date)
    end

    plaid_items.each do |plaid_item|
      plaid_item.sync_later(start_date: start_date)
    end
  end

  def post_sync
    broadcast_refresh
  end

  def syncing?
    Sync.where(
      "(syncable_type = 'Family' AND syncable_id = ?) OR
       (syncable_type = 'Account' AND syncable_id IN (SELECT id FROM accounts WHERE family_id = ? AND plaid_account_id IS NULL)) OR
       (syncable_type = 'PlaidItem' AND syncable_id IN (SELECT id FROM plaid_items WHERE family_id = ?))",
      id, id, id
    ).where(status: [ "pending", "syncing" ]).exists?
  end

  def eu?
    country != "US" && country != "CA"
  end

  def get_link_token(webhooks_url:, redirect_url:, accountable_type: nil, region: :us, access_token: nil)
    provider = if region.to_sym == :eu
      Provider::Registry.get_provider(:plaid_eu)
    else
      Provider::Registry.get_provider(:plaid_us)
    end

    # early return when no provider
    return nil unless provider

    provider.get_link_token(
      user_id: id,
      webhooks_url: webhooks_url,
      redirect_url: redirect_url,
      accountable_type: accountable_type,
      access_token: access_token
    ).link_token
  end

  def subscribed?
    stripe_subscription_status == "active"
  end

  def requires_data_provider?
    # If family has any trades, they need a provider for historical prices
    return true if trades.any?

    # If family has any accounts not denominated in the family's currency, they need a provider for historical exchange rates
    return true if accounts.where.not(currency: self.currency).any?

    # If family has any entries in different currencies, they need a provider for historical exchange rates
    uniq_currencies = entries.pluck(:currency).uniq
    return true if uniq_currencies.count > 1
    return true if uniq_currencies.count > 0 && uniq_currencies.first != self.currency

    false
  end

  def primary_user
    users.order(:created_at).first
  end

  def oldest_entry_date
    entries.order(:date).first&.date || Date.current
  end

  def active_accounts_count
    accounts.active.count
  end

  # Cache key that is invalidated when any of the family's entries are updated (which affect rollups and other calculations)
  def build_cache_key(key)
    [
      "family",
      id,
      key,
      entries.maximum(:updated_at)
    ].compact.join("_")
  end
end

app/models/transaction/enriched.rb
module Transaction::Enriched
  include Providable

  def fetch_merchant_data_from_provider
    response = merchant_data_provider.fetch_merchant_data(description: notes)

    if response.success?
      Merchant.new \
        name: response.name,
        website: response.website,
        logo_url: response.logo_url
    else
      # do something else
    end
  end
end

app/models/transaction/provided.rb
module Transaction::Provided
  include Providable

  def fetch_merchant_data_from_provider
    response = merchant_data_provider.fetch_merchant_data(description: notes)

    if response.success?
      Merchant.new \
        name: response.name,
        website: response.website,
        logo_url: response.logo_url
    else
      # do something else
    end
  end
end

app/models/transaction/tag.rb
class Transaction::Tag < ApplicationRecord
  belongs_to :family

  validates :name, :family, presence: true
  scope :alphabetically, -> { order(:name) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[]
  end
end

app/controllers/account/transactions_controller.rb
class Account::TransactionsController < ApplicationController
  include EntryableResource

  permitted_entryable_attributes :id, :category_id, :merchant_id, { tag_ids: [] }

  def bulk_delete
    destroyed = Current.family.entries.destroy_by(id: bulk_delete_params[:entry_ids])
    destroyed.map(&:account).uniq.each(&:sync_later)
    redirect_back_or_to transactions_url, notice: t(".success", count: destroyed.count)
  end

  def bulk_edit
  end

  def bulk_update
    updated = Current.family
                     .entries
                     .where(id: bulk_update_params[:entry_ids])
                     .bulk_update!(bulk_update_params)

    redirect_back_or_to transactions_url, notice: t(".success", count: updated)
  end

  private
    def bulk_delete_params
      params.require(:bulk_delete).permit(entry_ids: [])
    end

    def bulk_update_params
      params.require(:bulk_update).permit(:date, :notes, :category_id, :merchant_id, entry_ids: [], tag_ids: [])
    end

    def search_params
      params.fetch(:q, {})
            .permit(:start_date, :end_date, :search, :amount, :amount_operator, accounts: [], account_ids: [], categories: [], merchants: [], types: [], tags: [])
    end
end

app/controllers/transaction/rows_controller.rb
class Transaction::RowsController < ApplicationController
  before_action :set_transaction, only: %i[ show update ]

  def show
  end

  def update
    @transaction.update! transaction_params

    redirect_to transaction_row_path(@transaction)
  end

  private

    def transaction_params
      params.require(:transaction).permit(:category_id)
    end

    def set_transaction
      @transaction = Current.family.transactions.find(params[:id])
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include ScrollFocusable

  before_action :store_params!, only: :index

  def index
    @q = search_params
    transactions_query = Current.family.transactions.active.search(@q)

    set_focused_record(transactions_query, params[:focused_record_id], default_per_page: 50)

    @pagy, @transactions = pagy(
      transactions_query.includes(
        { entry: :account },
        :category, :merchant, :tags,
        transfer_as_outflow: { inflow_transaction: { entry: :account } },
        transfer_as_inflow: { outflow_transaction: { entry: :account } }
      ).reverse_chronological,
      limit: params[:per_page].presence || default_params[:per_page],
      params: ->(params) { params.except(:focused_record_id) }
    )

    @totals = Current.family.income_statement.totals(transactions_scope: transactions_query)
  end

  def clear_filter
    updated_params = {
      "q" => search_params,
      "page" => params[:page],
      "per_page" => params[:per_page]
    }

    q_params = updated_params["q"] || {}

    param_key = params[:param_key]
    param_value = params[:param_value]

    if q_params[param_key].is_a?(Array)
      q_params[param_key].delete(param_value)
      q_params.delete(param_key) if q_params[param_key].empty?
    else
      q_params.delete(param_key)
    end

    updated_params["q"] = q_params.presence
    Current.session.update!(prev_transaction_page_params: updated_params)

    redirect_to transactions_path(updated_params)
  end

  private

    def search_params
      cleaned_params = params.fetch(:q, {})
            .permit(
              :start_date, :end_date, :search, :amount,
              :amount_operator, accounts: [], account_ids: [],
              categories: [], merchants: [], types: [], tags: []
            )
            .to_h
            .compact_blank

      cleaned_params.delete(:amount_operator) unless cleaned_params[:amount].present?

      cleaned_params
    end

    def store_params!
      if should_restore_params?
        params_to_restore = {}

        params_to_restore[:q] = stored_params["q"].presence || default_params[:q]
        params_to_restore[:page] = stored_params["page"].presence || default_params[:page]
        params_to_restore[:per_page] = stored_params["per_page"].presence || default_params[:per_page]

        redirect_to transactions_path(params_to_restore)
      else
        Current.session.update!(
          prev_transaction_page_params: {
            q: search_params,
            page: params[:page],
            per_page: params[:per_page]
          }
        )
      end
    end

    def should_restore_params?
      request.query_parameters.blank? && (stored_params["q"].present? || stored_params["page"].present? || stored_params["per_page"].present?)
    end

    def stored_params
      Current.session.prev_transaction_page_params
    end

    def default_params
      {
        q: {},
        page: 1,
        per_page: 50
      }
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transaction_search_filters
    [
      { key: "account_filter", icon: "layers" },
      { key: "date_filter", icon: "calendar" },
      { key: "type_filter", icon: "tag" },
      { key: "amount_filter", icon: "hash" },
      { key: "category_filter", icon: "shapes" },
      { key: "tag_filter", icon: "tags" },
      { key: "merchant_filter", icon: "store" }
    ]
  end

  def get_transaction_search_filter_partial_path(filter)
    "transactions/searches/filters/#{filter[:key]}"
  end

  def get_default_transaction_search_filter
    transaction_search_filters[0]
  end
end

app/views/transactions/_header.html.erb
<header class="flex justify-between items-center text-primary font-medium">
  <h1 class="text-xl">Transactions</h1>
  <div class="flex items-center gap-5">
    <div class="flex items-center gap-2">
      <%= contextual_menu do %>
        <%= contextual_menu_modal_action_item t(".edit_categories"), categories_path, icon: "shapes", turbo_frame: :_top %>
        <%= contextual_menu_modal_action_item t(".edit_tags"), tags_path, icon: "tags", turbo_frame: :_top %>
        <%= contextual_menu_modal_action_item t(".edit_merchants"), merchants_path, icon: "store", turbo_frame: :_top %>
        <%= contextual_menu_modal_action_item t(".edit_imports"), imports_path, icon: "hard-drive-upload", turbo_frame: :_top %>
      <% end %>

      <%= link_to new_import_path, class: "btn btn--outline flex items-center gap-2", data: { turbo_frame: "modal" } do %>
        <%= lucide_icon("download", class: "text-secondary w-4 h-4") %>
        <p class="text-sm font-medium text-primary"><%= t(".import") %></p>
      <% end %>

      <%= link_to new_account_transaction_path, class: "btn btn--primary flex items-center gap-2", data: { turbo_frame: :modal } do %>
        <%= lucide_icon("plus", class: "w-5 h-5") %>
        <p class="text-sm font-medium">New transaction</p>
      <% end %>
    </div>
  </div>
</header>

app/views/transactions/_selection_bar.html.erb
<div class="fixed bottom-6 z-10 flex items-center justify-between rounded-xl bg-gray-900 px-4 text-sm text-white w-[420px] py-1.5">
  <div class="flex items-center gap-2">
    <%= check_box_tag "transaction_selection", 1, true, class: "maybe-checkbox maybe-checkbox--dark", data: { action: "bulk-select#deselectAll" } %>

    <p data-bulk-select-target="selectionBarText"></p>
  </div>

  <div class="flex items-center gap-1 text-gray-500">
    <%= turbo_frame_tag "bulk_transaction_edit_drawer" %>

    <%= form_with url: mark_transfers_transactions_path,
                  builder: ActionView::Helpers::FormBuilder,
                  scope: "bulk_update",
                  data: {
                    turbo_confirm: {
                      title: t(".mark_transfers"),
                      body: t(".mark_transfers_message"),
                      accept: t(".mark_transfers_confirm"),
                    }
                  } do |f| %>
      <button id="bulk-transfer-btn" type="button" data-bulk-select-scope-param="bulk_update" data-action="bulk-select#submitBulkRequest" class="p-1.5 group hover:bg-gray-700 flex items-center justify-center rounded-md" title="Mark as transfer">
        <%= lucide_icon "arrow-right-left", class: "w-5 group-hover:text-white" %>
      </button>
    <% end %>

    <%= link_to bulk_edit_transactions_path,
                class: "p-1.5 group hover:bg-gray-700 flex items-center justify-center rounded-md",
                title: "Edit",
                data: { turbo_frame: "bulk_transaction_edit_drawer" } do %>
      <%= lucide_icon "pencil-line", class: "w-5 group-hover:text-white" %>
    <% end %>

    <%= form_with url: bulk_delete_transactions_path, builder: ActionView::Helpers::FormBuilder, data: { turbo_confirm: true } do %>
      <button type="button" data-bulk-select-scope-param="bulk_delete" data-action="bulk-select#submitBulkRequest" class="p-1.5 group hover:bg-gray-700 flex items-center justify-center rounded-md" title="Delete">
        <%= lucide_icon "trash-2", class: "w-5 group-hover:text-white" %>
      </button>
    <% end %>
  </div>
</div>

app/views/transactions/_summary.html.erb
<%# locals: (totals:) %>
<div class="grid grid-cols-3 bg-white rounded-xl shadow-border-xs divide-x divide-alpha-black-100">
  <div class="p-4 space-y-2">
    <p class="text-sm text-secondary">Total transactions</p>
    <p class="text-primary font-medium text-xl" id="total-transactions"><%= totals.transactions_count.round(0) %></p>
  </div>
  <div class="p-4 space-y-2">
    <p class="text-sm text-secondary">Income</p>
    <p class="text-primary font-medium text-xl" id="total-income">
      <%= totals.income_money.format %>
    </p>
  </div>
  <div class="p-4 space-y-2">
    <p class="text-sm text-secondary">Expenses</p>
    <p class="text-primary font-medium text-xl" id="total-expense">
      <%= totals.expense_money.format %>
    </p>
  </div>
</div>

app/views/transactions/category_menu.html.erb
<%= turbo_frame_tag "category_menu_content" do %>
  <div class="flex flex-col relative" data-controller="list-filter">
    <div class="grow p-1.5">
      <div class="relative flex items-center bg-white border border-gray-200 rounded-lg">
        <input placeholder="Search" autocomplete="nope" type="search" class="placeholder:text-sm placeholder:text-gray-500 font-normal h-10 relative pl-10 w-full border-none rounded-lg" data-list-filter-target="input" data-action="list-filter#filter">
        <%= lucide_icon("search", class: "w-5 h-5 text-gray-500 ml-2 absolute inset-0 transform top-1/2 -translate-y-1/2") %>
      </div>
    </div>
    <div data-list-filter-target="list" class="flex flex-col gap-0.5 p-1.5 mt-0.5 mr-2 max-h-64 overflow-y-scroll scrollbar">
      <div class="pb-2 pl-4 mr-2 text-gray-500 hidden" data-list-filter-target="emptyMessage">
        No categories found
      </div>
      <% sorted_categories = Current.family.transaction_categories.sort_by { |category| category.id == @transaction.category_id ? 0 : 1 } %>
      <% sorted_categories.each do |category| %>
        <%= render partial: "transactions/categories/dropdown/row", locals: { category:, transaction: @transaction } %>
      <% end %>
    </div>
    <hr>
    <div class="relative p-1.5 w-full">
      <%= link_to new_transaction_category_path(transaction_id: @transaction),
                  class: "flex text-sm font-medium items-center gap-2 text-gray-500 w-full rounded-lg p-2 hover:bg-gray-100",
                  data: { turbo_frame: "modal" } do %>
        <%= lucide_icon "plus", class: "w-5 h-5" %>

        <%= t(".add_new") %>
      <% end %>

      <% if @transaction.category %>
        <%= button_to transaction_path(@transaction),
                      method: :patch,
                      params: { transaction: { category_id: nil } },
                      class: "flex text-sm font-medium items-center gap-2 text-gray-500 w-full rounded-lg p-2 hover:bg-gray-100" do %>
          <%= lucide_icon "minus", class: "w-5 h-5" %>

          <%= t(".clear") %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/transactions/category_menu_content.erb
<%= turbo_frame_tag "category_menu_content" do %>
  <div class="flex flex-col relative" data-controller="list-filter">
    <div class="grow p-1.5">
      <div class="relative flex items-center bg-white border border-gray-200 rounded-lg">
        <input placeholder="Search" autocomplete="nope" type="search" class="placeholder:text-sm placeholder:text-gray-500 font-normal h-10 relative pl-10 w-full border-none rounded-lg" data-list-filter-target="input" data-action="list-filter#filter">
        <%= lucide_icon("search", class: "w-5 h-5 text-gray-500 ml-2 absolute inset-0 transform top-1/2 -translate-y-1/2") %>
      </div>
    </div>
    <div data-list-filter-target="list" class="flex flex-col gap-0.5 p-1.5 mt-0.5 mr-2 max-h-64 overflow-y-scroll scrollbar">
      <div class="pb-2 pl-4 mr-2 text-gray-500 hidden" data-list-filter-target="emptyMessage">
        No categories found
      </div>
      <% sorted_categories = Current.family.transaction_categories.sort_by { |category| category.id == @transaction.category_id ? 0 : 1 } %>
      <% sorted_categories.each do |category| %>
        <%= render partial: "transactions/categories/dropdown/row", locals: { category:, transaction: @transaction } %>
      <% end %>
    </div>
    <hr>
    <div class="relative p-1.5 w-full">
      <%= link_to new_transaction_category_path(transaction_id: @transaction),
                  class: "flex text-sm font-medium items-center gap-2 text-gray-500 w-full rounded-lg p-2 hover:bg-gray-100",
                  data: { turbo_frame: "modal" } do %>
        <%= lucide_icon "plus", class: "w-5 h-5" %>

        <%= t(".add_new") %>
      <% end %>

      <% if @transaction.category %>
        <%= button_to transaction_path(@transaction),
                      method: :patch,
                      params: { transaction: { category_id: nil } },
                      class: "flex text-sm font-medium items-center gap-2 text-gray-500 w-full rounded-lg p-2 hover:bg-gray-100" do %>
          <%= lucide_icon "minus", class: "w-5 h-5" %>

          <%= t(".clear") %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/transactions/index.html.erb
<div class="space-y-4 pb-20 flex flex-col" data-controller="focus-record" data-focus-record-id-value="<%= @focused_record ? dom_id(@focused_record) : nil %>">
  <%= render "header" %>

  <%= render "summary", totals: @totals %>

  <div id="transactions"
       data-controller="bulk-select"
       data-bulk-select-singular-label-value="<%= t(".transaction") %>"
       data-bulk-select-plural-label-value="<%= t(".transactions") %>"
       class="flex flex-col bg-white rounded-xl shadow-border-xs p-4">
    <%= render "transactions/searches/search" %>

    <div id="entry-selection-bar" data-bulk-select-target="selectionBar" class="flex justify-center hidden">
      <%= render "account/transactions/selection_bar" %>
    </div>

    <% if @pagy.count > 0 %>
      <div class="grow overflow-y-auto">
        <div class="grid grid-cols-12 bg-gray-25 rounded-xl px-5 py-3 text-xs uppercase font-medium text-secondary items-center mb-4">
          <div class="pl-0.5 col-span-8 flex items-center gap-4">
            <%= check_box_tag "selection_entry",
                              class: "checkbox checkbox--light",
                              data: { action: "bulk-select#togglePageSelection" } %>
            <p>transaction</p>
          </div>

          <p class="col-span-2">category</p>
          <p class="col-span-2 justify-self-end">amount</p>
        </div>
        <div class="space-y-6">
          <%= entries_by_date(@transactions.map(&:entry), totals: true) do |entries| %>
            <%= render entries %>
          <% end %>
        </div>
      </div>
    <% else %>
      <%= render "account/entries/empty" %>
    <% end %>

    <div class="pt-4">
      <%= render "shared/pagination", pagy: @pagy %>
    </div>
  </div>
</div>